import { SupportPage } from "@/components/SupportPage";

export default function SafetyPage() {
  return (
    <SupportPage
      title="Safety"
      intro="At TARIA, safety is not an add-on — it is the foundation of the platform."
      paragraphs={[
        "The platform is built to protect users, partners, and institutions through secure architecture, encrypted data handling, and controlled access protocols.",
        "TARIA operates within industry best practices and regulatory standards, supporting banks, MFIs, and insurers to distribute insurance responsibly and transparently.",
        "All recommendations generated by TARIA are advisory in nature and aligned with approved underwriting rules.",
      ]}
    />
  );
}
